In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# Verbindung zur Datenbank herstellen
engine = create_engine("mysql+mysqlconnector://root:root@localhost:3306/football_db", echo=False)

In [3]:
query_appearances = "SELECT * FROM appearances WHERE date >= '2021-01-01';"
df_appearances = pd.read_sql_query(query_appearances, engine)
df_appearances.head(10)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,...,shot attempt,goal assists,successful passes,attempted passes,pass accuracy in %,progressive passes,carries,progressive runs,attempted dribbles,successful dribbling
0,3393783_106721,3393783,106721,370,2553,2021-02-17,Ash Taylor,SC1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3393783_120976,3393783,120976,370,370,2021-02-17,Dylan McGeouch,SC1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3393783_120977,3393783,120977,371,371,2021-02-17,Callum McGregor,SC1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3393783_12688,3393783,12688,371,370,2021-02-17,Scott Brown,SC1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3393783_132207,3393783,132207,370,2553,2021-02-17,Matty Kennedy,SC1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3393783_183161,3393783,183161,370,370,2021-02-17,Tommie Hoban,SC1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3393783_186644,3393783,186644,371,190,2021-02-17,Mohamed Elyounoussi,SC1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,3393783_188077,3393783,188077,371,989,2021-02-17,Ryan Christie,SC1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,3393783_195906,3393783,195906,371,371,2021-02-17,Albian Ajeti,SC1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3393783_21306,3393783,21306,370,2578,2021-02-17,Andy Considine,SC1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_appearances.shape

(446793, 38)

In [6]:
query_club_games = "SELECT * FROM club_games WHERE game_id IN (SELECT game_id FROM games WHERE season >= 2021);"
df_club_games = pd.read_sql_query(query_club_games, engine)
df_club_games.head(10)

,id,game_id,club_id,own_goals,own_position,own_manager_name,opponent_id,opponent_goals,opponent_position,opponent_manager_name,hosting,is_win
0,64367,3573730,1082,1,NaN,Jocelyn Gourvennec,583,0,NaN,Mauricio Pochettino,Home,1
1,131052,3573730,583,0,NaN,Mauricio Pochettino,1082,1,NaN,Jocelyn Gourvennec,Away,0
2,23330,3575344,16,1,NaN,Marco Rose,27,3,NaN,Julian Nagelsmann,Home,0
3,90015,3575344,27,3,NaN,Julian Nagelsmann,16,1,NaN,Marco Rose,Away,1
4,60208,3578075,1003,1,NaN,Brendan Rodgers,281,0,NaN,Pep Guardiola,Home,1
5,126893,3578075,281,0,NaN,Pep Guardiola,1003,1,NaN,Brendan Rodgers,Away,0
6,23331,3580162,865,1,10.0,Bo Henriksen,173,2,2.0,Andreas Alm,Home,0
7,90016,3580162,173,2,2.0,Andreas Alm,865,1,10.0,Bo Henriksen,Away,1
8,10964,3580163,2778,1,11.0,Flemming Pedersen,1063,2,3.0,Lars Friis,Home,0
9,77649,3580163,1063,2,3.0,Lars Friis,2778,1,11.0,Flemming Pedersen,Away,1

In [7]:
df_club_games.shape

(31942, 12)

In [8]:
query_clubs = "SELECT * FROM clubs;"
df_clubs = pd.read_sql_query(query_clubs, engine)
df_clubs.head(10)

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,3,1-fc-koln,1. FuÃŸball-Club KÃ¶ln,L1,None,29,25.0,7,24.0,4,RheinEnergieSTADION,50000,+â‚¬200k,None,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/1-fc-koln/star...
1,4,1-fc-nurnberg,1.FC Nuremberg,L1,None,33,25.0,7,21.0,2,Max-Morlock-Stadion,50000,+â‚¬2.63m,None,2018,../data/raw/transfermarkt-scraper/2018/clubs.j...,https://www.transfermarkt.co.uk/1-fc-nurnberg/...
2,5,ac-mailand,Associazione Calcio Milan,IT1,None,26,27.0,17,65.0,14,Giuseppe Meazza,75923,â‚¬-50.40m,None,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/ac-mailand/sta...
3,6,adanaspor,Adanaspor,TR1,None,10,24.0,4,40.0,0,Yeni Adana Stadyumu,33000,+-0,None,2016,../data/raw/transfermarkt-scraper/2016/clubs.j...,https://www.transfermarkt.co.uk/adanaspor/star...
4,10,arminia-bielefeld,Arminia Bielefeld,L1,None,27,25.0,15,56.0,4,SchÃ¼coArena,26515,+â‚¬5.90m,None,2021,../data/raw/transfermarkt-scraper/2021/clubs.j...,https://www.transfermarkt.co.uk/arminia-bielef...
5,11,fc-arsenal,Arsenal Football Club,GB1,None,25,26.0,18,72.0,20,Emirates Stadium,60704,â‚¬-167.04m,None,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/fc-arsenal/sta...
6,12,as-rom,Associazione Sportiva Roma,IT1,None,27,27.0,18,67.0,16,Olimpico di Roma,73261,+â‚¬63.00m,None,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
7,13,atletico-madrid,Club AtlÃ©tico de Madrid S.A.D.,ES1,None,25,29.0,16,64.0,14,Civitas Metropolitano,70460,+â‚¬50.60m,None,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/atletico-madri...
8,15,bayer-04-leverkusen,Bayer 04 Leverkusen FuÃŸball,L1,None,27,25.0,22,82.0,19,BayArena,30210,â‚¬-12.60m,None,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/bayer-04-lever...
9,16,borussia-dortmund,Borussia Dortmund,L1,None,28,25.0,13,46.0,16,SIGNAL IDUNA PARK,81365,+â‚¬48.85m,None,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/borussia-dortm...

In [9]:
df_clubs.shape

(426, 17)

In [10]:
query_competition = "SELECT * FROM competition;"
df_competition = pd.read_sql_query(query_competition, engine)
df_competition.head(10)

,competition_id,competition_code,name,sub_type,type,country_id,contry_name,domestic_league_code,confederation,url
0,BE1,jupiler-pro-league,jupiler-pro-league,first_tier,domestic_league,19,Belgium,BE1,europa,https://www.transfermarkt.co.uk/jupiler-pro-le...
1,BESC,belgian-supercup,belgian-supercup,domestic_super_cup,other,19,Belgium,BE1,europa,https://www.transfermarkt.co.uk/belgian-superc...
2,CDR,copa-del-rey,copa-del-rey,domestic_cup,domestic_cup,157,Spain,ES1,europa,https://www.transfermarkt.co.uk/copa-del-rey/s...
3,CGB,efl-cup,efl-cup,league_cup,other,189,England,GB1,europa,https://www.transfermarkt.co.uk/efl-cup/starts...
4,CIT,italy-cup,italy-cup,domestic_cup,domestic_cup,75,Italy,IT1,europa,https://www.transfermarkt.co.uk/italy-cup/star...
5,CL,uefa-champions-league,uefa-champions-league,uefa_champions_league,international_cup,-1,None,None,europa,https://www.transfermarkt.co.uk/uefa-champions...
6,CLQ,uefa-champions-league-qualifikation,uefa-champions-league-qualifikation,uefa_champions_league_qualifying,international_cup,-1,None,None,europa,https://www.transfermarkt.co.uk/uefa-champions...
7,DFB,dfb-pokal,dfb-pokal,domestic_cup,domestic_cup,40,Germany,L1,europa,https://www.transfermarkt.co.uk/dfb-pokal/star...
8,DFL,dfl-supercup,dfl-supercup,domestic_super_cup,other,40,Germany,L1,europa,https://www.transfermarkt.co.uk/dfl-supercup/s...
9,DK1,superligaen,superligaen,first_tier,domestic_league,39,Denmark,DK1,europa,https://www.transfermarkt.co.uk/superligaen/st...

In [11]:
df_competition.shape

(43, 10)

In [12]:
query_game_events = "SELECT * FROM game_events WHERE game_id IN (SELECT game_id FROM games WHERE season >= 2021);"
df_game_events = pd.read_sql_query(query_game_events, engine)
df_game_events.head(10)

,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id
0,1d01e32b2bd5d0629f4f600367664512,2021-08-01,3573730,71,Substitutions,583,536482,None,49499.0,None
1,2881fe99d9d50c18290ede6ffcd7312d,2021-08-01,3573730,79,Substitutions,1082,290256,None,386726.0,None
2,3482ba581e53b74660f4b15ccfd68ef6,2021-08-01,3573730,45,Goals,1082,290256,", Right-footed shot, 1. Tournament Goal",None,None
3,96ea0817d233416a0cf4b898186fdca9,2021-08-01,3573730,81,Substitutions,583,282041,None,126710.0,None
4,9d1a937ab9e42daf4b8063b4a127fb2c,2021-08-01,3573730,76,Substitutions,1082,533738,None,370846.0,None
5,b098b8427ba4bb76c4049fe6faaa6c2e,2021-08-01,3573730,85,Substitutions,1082,292818,None,357796.0,None
6,b2b0f6ffcdcf2302c4b0cb00ef2d332d,2021-08-01,3573730,85,Substitutions,1082,435485,None,324690.0,None
7,d7641d205d02cbed0b76e67a1045c11e,2021-08-01,3573730,81,Substitutions,583,585959,None,810096.0,None
8,08040928f279a6b15a9f7b31df1ee123,2021-08-17,3575344,41,Goals,27,38253,", Header, 1. Tournament Goal",None,None
9,1b1fc23efbf14d211b2dcfb795425348,2021-08-17,3575344,49,Goals,27,58358,", Tap-in, 1. Tournament Goal",None,None

In [13]:
df_game_events.shape

(200297, 10)

In [14]:
query_game_lineups = "SELECT * FROM game_lineups WHERE game_id IN (SELECT game_id FROM games WHERE season >= 2021);"
df_game_lineups = pd.read_sql_query(query_game_lineups, engine)
df_game_lineups.head(10)

,game_lineups_id,game_id,club_id,type,number,player_id,player_name,team_captain,position
0,0986b2bf40d93e365939af5052e1f5f9,3573730,1082,starting_lineup,30.0,288415,LÃ©o Jardim,0,Goalkeeper
1,0ebb44f2a0d55bd56357f3ddd8977425,3573730,583,starting_lineup,23.0,85148,Julian Draxler,0,Right Winger
2,11cc8eb76c94f03f845afa7176ab5ae9,3573730,583,substitutes,20.0,126710,Layvin Kurzawa,0,Left-Back
3,17fe27bca6029817abfccb739674a4be,3573730,1082,starting_lineup,3.0,420465,Tiago DjalÃ³,0,Right-Back
4,1fceaed471d0aa9f6ec0695b3220b8a2,3573730,1082,starting_lineup,9.0,533738,Jonathan David,0,Second Striker
5,227a05be666b58ea7ffcc04bc33ec4cb,3573730,1082,starting_lineup,4.0,361093,Sven Botman,0,Centre-Back
6,2831cb077d9a3cefc35f20093a899285,3573730,1082,substitutes,35.0,392770,Angel Gomes,0,Central Midfield
7,2960faf0e57c0e43e13f096de9e6e130,3573730,1082,substitutes,19.0,557610,Isaac Lihadji,0,Right Winger
8,3230388abeab06f0b2450913be42b50a,3573730,583,substitutes,34.0,566931,Xavi Simons,0,Right Winger
9,3d6e06aca83af67328b13c16ab0a47b5,3573730,1082,substitutes,10.0,324690,Jonathan IkonÃ©,0,Right Winger

In [16]:
df_game_lineups.shape

(648687, 9)

In [17]:
query_games = "SELECT * FROM games WHERE season >= 2021;"
df_games = pd.read_sql_query(query_games, engine)
df_games.head(10)

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,3573730,FRCH,2021,Final,2021-08-01,1082,583,1,0,NaN,...,Bloomfield,29000.0,Igal Frid,https://www.transfermarkt.co.uk/spielbericht/i...,4-4-2 double 6,4-3-3 Attacking,Lille Olympique Sporting Club Lille MÃ©tropole,Paris Saint-Germain Football Club,1:0,other
1,3575344,DFL,2021,Final,2021-08-17,16,27,1,3,NaN,...,SIGNAL IDUNA PARK,25000.0,Sascha Stegemann,https://www.transfermarkt.co.uk/spielbericht/i...,4-4-2 Diamond,4-2-3-1,Borussia Dortmund,FC Bayern MÃ¼nchen,1:3,other
2,3578075,GBCS,2021,Final,2021-08-07,1003,281,1,0,NaN,...,Wembley Stadium,45602.0,Paul Tierney,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-3-3 Attacking,Leicester City,Manchester City Football Club,1:0,other
3,3580162,DK1,2021,1. Matchday,2021-07-16,865,173,1,2,10.0,...,MCH Arena,4890.0,Sandi Putros,https://www.transfermarkt.co.uk/fc-midtjylland...,4-3-3 Attacking,4-2-3-1,Fodbold Club Midtjylland,Odense Boldklub,1:2,domestic_league
4,3580163,DK1,2021,1. Matchday,2021-07-18,2778,1063,1,2,11.0,...,Right to Dream Park,2000.0,Morten Krogh,https://www.transfermarkt.co.uk/fc-nordsjaella...,3-4-3,4-3-3 Attacking,Fodbold Club NordsjÃ¦lland,Viborg Fodsports Forening,1:2,domestic_league
5,3580164,DK1,2021,1. Matchday,2021-07-18,443,5724,0,2,12.0,...,Vejle Stadion,3350.0,Jonas Hansen,https://www.transfermarkt.co.uk/vejle-boldklub...,4-2-3-1,4-4-2,Vejle Boldklub,Randers Fodbold Club,0:2,domestic_league
6,3580165,DK1,2021,1. Matchday,2021-07-18,190,1053,2,2,4.0,...,Parken,13326.0,Mads-Kristoffer Kristoffersen,https://www.transfermarkt.co.uk/fc-copenhagen_...,4-3-3 Attacking,3-4-3,Football Club KÃ¸benhavn,Aalborg BK,2:2,domestic_league
7,3580166,DK1,2021,1. Matchday,2021-07-18,678,206,1,1,7.0,...,Ceres Park,8392.0,Jens Maae,https://www.transfermarkt.co.uk/aarhus-gf_bron...,4-3-3 Attacking,3-5-2,Aarhus Gymnastik Forening,BrÃ¸ndby IdrÃ¦tsforening,1:1,domestic_league
8,3580167,DK1,2021,1. Matchday,2021-07-19,1177,5817,0,0,8.0,...,JYSK Park,2174.0,Mikkel Redder,https://www.transfermarkt.co.uk/silkeborg-if_s...,4-3-3 Attacking,4-3-3 Attacking,Silkeborg IdrÃ¦tsforening,SÃ¶nderjyskE,0:0,domestic_league
9,3580175,DK1,2021,2. Matchday,2021-07-24,1053,865,0,1,10.0,...,Aalborg Portland Park,3784.0,Jakob Kehlet,https://www.transfermarkt.co.uk/aalborg-bk_fc-...,4-2-3-1,3-4-3,Aalborg BK,Fodbold Club Midtjylland,0:1,domestic_league

In [18]:
df_games.shape

(15971, 23)

In [19]:
query_player_valuations = "SELECT * FROM player_valuations WHERE date >= '2021-01-01';"
df_player_valuations = pd.read_sql_query(query_player_valuations, engine)
df_player_valuations.head(10)

,id,player_id,date,market_value_in_eur,current_club_id,player_club_domestic_competition_id
0,338248,38000,2021-01-01,150000,2861,BE1
1,338249,66613,2021-01-01,150000,441,GR1
2,338250,74253,2021-01-01,50000,1025,IT1
3,338251,106181,2021-01-01,250000,3558,FR1
4,338252,126673,2021-01-01,3500000,1025,IT1
5,338253,147490,2021-01-01,75000,1084,ES1
6,338254,262682,2021-01-01,150000,173,DK1
7,338255,28171,2021-01-02,75000,1084,ES1
8,338256,33448,2021-01-02,75000,130,IT1
9,338257,34116,2021-01-02,75000,173,DK1

In [20]:
df_player_valuations.shape

(127074, 6)

In [21]:
query_players = "SELECT * FROM players;"
df_players = pd.read_sql_query(query_players, engine)
df_players.head(10)

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,None,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,SocietÃ Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,None,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,None,NaN,None,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,None,LÃºcio,LÃºcio,2012,506,lucio,Brazil,BrasÃ­lia,Brazil,...,None,NaN,None,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,None,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern MÃ¼nchen,100000.0,3000000.0
5,109,None,DedÃª,DedÃª,2013,825,dede,Brazil,Belo Horizonte,Brazil,...,None,NaN,None,Football Concept,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dede/profil/sp...,TR1,Eskisehirspor,400000.0,9500000.0
6,123,Christoph,Metzelder,Christoph Metzelder,2012,33,christoph-metzelder,Germany,Haltern,Germany,...,None,NaN,None,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/christoph-metz...,L1,FC Schalke 04,1500000.0,9500000.0
7,132,Tomas,Rosicky,Tomas Rosicky,2015,11,tomas-rosicky,CSSR,Praha,Czech Republic,...,both,179.0,None,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tomas-rosicky/...,GB1,Arsenal Football Club,350000.0,17500000.0
8,162,Marc,Ziegler,Marc Ziegler,2012,79,marc-ziegler,Germany,Blieskastel,Germany,...,right,193.0,None,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/marc-ziegler/p...,L1,Verein fÃ¼r Bewegungsspiele Stuttgart 1893,200000.0,1250000.0
9,215,Roque,Santa Cruz,Roque Santa Cruz,2015,1084,roque-santa-cruz,Paraguay,AsunciÃ³n,Paraguay,...,right,193.0,2023-12-31 00:00:00,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roque-santa-cr...,ES1,MÃ¡laga CF,250000.0,12000000.0

In [22]:
df_players.shape

(30500, 23)

In [2]:
import os

# Erstelle den Ordner, wenn er nicht existiert
output_folder = "C:/Users/Richa/Desktop/business-intelligence-football-data/data/OLAP data"
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Speichere jeden DataFrame als CSV in dem Ordner
df_appearances.to_csv(f"{output_folder}/df_appearances.csv", index=False)
df_club_games.to_csv(f"{output_folder}/df_club_games.csv", index=False)
df_clubs.to_csv(f"{output_folder}/df_clubs.csv", index=False)
df_competition.to_csv(f"{output_folder}/df_competition.csv", index=False)
df_game_events.to_csv(f"{output_folder}/df_game_events.csv", index=False)
df_game_lineups.to_csv(f"{output_folder}/df_game_lineups.csv", index=False)
df_games.to_csv(f"{output_folder}/df_games.csv", index=False)
df_player_valuations.to_csv(f"{output_folder}/df_player_valuations.csv", index=False)
df_players.to_csv(f"{output_folder}/df_players.csv", index=False)

NameError: name 'df_appearances' is not defined